### ISSUE TITLE
发布文章流程不清晰，没有发布按钮

### ISSUE THREAD

**Issue by jialiangZ** [dafengzhen/youdeyiwu-docs#28]
![image](https://github.com/dafengzhen/youdeyiwu-docs/assets/54654343/d0e22cd9-f515-4cab-ae4f-5b43b1251dc0)
这个界面的流程不够简洁明了

**Comment by dafengzhen** [comment]
感谢反馈

标题的右边有个 "保存" 按钮，保存后会发布
把按钮放在编辑器底下，文字改为 “发布” 会不会好点

**Comment by jialiangZ** [comment]
是的，这样更简单明了
